application: omnichat
version: 1
runtime: python
api_version: 1

handlers:
- url: /js
  static_dir: js
- url: /images
  static_dir: images
- url: /css
  static_dir: css
- url: /
  static_dir: pages
- url: /.*
  static_dir: pages
- url: /img
  static_dir: img
- url: /locale
  static_dir: locale
- url: /locale
  static_dir: locale
- url: /snd
  static_dir: snd


